OrderToFood/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrderToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OrderToFood/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrderToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OrderToFood/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrderToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OrderToFood/Pages/Resturants/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Resturant.Core;
using Resturant.Data;

namespace OrderToFood.Pages.Resturants
{
    public class DeleteModel : PageModel
    {
        public ResturantsHotel Resturant { get; set; }
        public IResturantData resturant { get; }

        public DeleteModel(IResturantData resturant)
        {
            this.resturant = resturant;
        }

        

        public IActionResult OnGet(int resturantId)
        {
            Resturant = resturant.GetResturantbyId(resturantId);
            if(Resturant == null)
            {
                return RedirectToPage("./NotFound404");
            }
            return Page();
        }

        public IActionResult OnPost(int resturantId)
        {
            Resturant = resturant.Delete(resturantId);            
            if(Resturant == null)
            {
                return RedirectToPage("./NotFound404");
            }
            resturant.commit();
            return RedirectToPage("./List");
        }
    }
}

OrderToFood/Pages/Resturants/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Resturant.Core;
using Resturant.Data;

namespace OrderToFood.Pages.Resturants
{
    public class DetailModel : PageModel
    {
        public ResturantsHotel resturant;
        private readonly IResturantData resturantData;
        [TempData]
        public string Message { get; set; }
        public DetailModel(IResturantData resturantData)
        {
            this.resturantData = resturantData;
        }
        public IActionResult OnGet(int resturantId)
        {
            resturant = resturantData.GetResturantbyId(resturantId);
            if(resturant == null)
            {
                return RedirectToPage("./NotFound404");
            }
            return Page();
        }
    }
}

OrderToFood/Pages/Resturants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Resturant.Core;
using Resturant.Data;

namespace OrderToFood.Pages.Resturants
{
    public class EditModel : PageModel
    {
        private readonly IResturantData resturantData;
        private readonly IHtmlHelper htmlHelper;
        public IEnumerable<SelectListItem> Cuisines;

        [BindProperty]
        public ResturantsHotel resturant { get; set; }

        public EditModel(IResturantData resturantData,IHtmlHelper htmlHelper)
        {
            this.resturantData = resturantData;
            this.htmlHelper = htmlHelper;
        }
        public IActionResult OnGet(int? resturantId)
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if(resturantId.HasValue)
            {
                resturant = resturantData.GetResturantbyId(resturantId.Value);
            }
            else
            {
                resturant = new ResturantsHotel();
            }
            
            if(resturant == null)
            {
                return RedirectToPage("./NotFound404");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            if(!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();                
            }
            if(resturant.Id> 0)
            {
                TempData["Message"] = "Updated the resturant";
                resturantData.Update(resturant);
            }
            else
            {
                TempData["Message"] = "Added new resturant";
                resturantData.Create(resturant);
            }
           
            resturantData.commit();
            return RedirectToPage("./Detail", new { resturantId = resturant.Id });
        }
    }
}

OrderToFood/Pages/Resturants/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Resturant.Data;
using Resturant.Core;

namespace OrderToFood.Pages.Resturants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly IResturantData resturantData;
        public IEnumerable<ResturantsHotel> resturants { get; set; }
        public string message { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public ListModel(IConfiguration config,IResturantData resturantData)
        {
            this._config = config;
            this.resturantData = resturantData;
        }
        public void OnGet()
        {
            message = "Welcome";
            resturants = resturantData.GetResturantsbyname(SearchTerm);
        }
    }
}

OrderToFood/Pages/Resturants/NotFound404.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrderToFood.Pages
{
    public class NotFound404Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OrderToFood/ViewComponents/ResturantViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resturant.Data;

namespace OrderToFood.ViewComponents
{
    public class ResturantViewComponent:ViewComponent
    {
        private readonly IResturantData resturantData;

        public ResturantViewComponent(IResturantData resturantData)
        {
            this.resturantData = resturantData;
        }

        public IViewComponentResult Invoke()
        {
            var count  = resturantData.getResturantCount();
            return View(count);
        }
    }
}

OrderToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OrderToFood/Pages/Resturants/Delete.cshtml
@page "{resturantId:int}"
@model OrderToFood.Pages.Resturants.DeleteModel
@{
	
}
<div class="alert alert-danger">
	Are you sure to delete @Model.Resturant.Name
	<form method="post">
		<button type="submit" class="btn btn-danger" asp-route-resturantId="@Model.Resturant.Id">Yes!</button>
		<a class="btn btn-secondary" asp-page="List">Cancel</a>
	</form>
</div>

OrderToFood/Pages/Resturants/Detail.cshtml
@page "{resturantId:int}"
@model OrderToFood.Pages.Resturants.DetailModel
@{

}
@if(Model.Message != null)
{
<div class="alert alert-primary">
	@Model.Message
</div>
}

<div>Resturant Name: @Model.resturant.Name</div>
<div>
	Id: @Model.resturant.Id
</div>
<div>
	Resturant Location: @Model.resturant.Location
</div>
<div>Resturant Cuisine Type: @Model.resturant.CusineType</div>

<a asp-page="./List" class="btn btn-danger" >All Resturants</a>

OrderToFood/Pages/Resturants/Edit.cshtml
@page "{resturantId:int?}"
@model OrderToFood.Pages.Resturants.EditModel
@{
}
<h2>Editing for @Model.resturant.Name</h2>
<form method="post">
	<input type="hidden" asp-for="@Model.resturant.Id"/>
	<div class="form-group">
		<label asp-for="@Model.resturant.Name"></label>
		<input asp-for="@Model.resturant.Name"/>
		<span class="text-danger" asp-validation-for="@Model.resturant.Name"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.resturant.Location"></label>
		<input asp-for="@Model.resturant.Location"/>
		<span class="text-danger" asp-validation-for="@Model.resturant.Location"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.resturant.CusineType"></label>
		<select asp-for="@Model.resturant.CusineType" asp-items="@Model.Cuisines">
			<span class="text-danger" asp-validation-for="@Model.resturant.CusineType"></span>

		</select>
	</div>
	<button type="submit" class="btn btn-primary">Save</button>
</form>

<a asp-page="./List" class="btn btn-primary">Back</a>

OrderToFood/Pages/Resturants/List.cshtml
@page
@model OrderToFood.Pages.Resturants.ListModel
@{
}
<h1>Resturants</h1>

<form method="GET">
	<div class="form-group">
		<div class="input-group">
			<input type = "search" class="form-control" asp-for="SearchTerm"/>
			<span class="input-group-btn">
				<button class="btn btn-success">
					Search
				</button>
			</span>
		</div>
	</div>
</form>

<table class="table">
	<tr>
		<td><b>Name</b></td>
		<td><b>Loaction</b></td>
		<td><b>Cusine Type</b></td>
		<td><b>Actions</b></td>
	</tr>
	
		@foreach (var res in Model.resturants)
		{
			<partial name="_Summary" model="res" />
		}
	
</table>

<a asp-page="./Edit" class="btn btn-primary">Create new Resturant</a>

@section footer
{
	@Model.message
}

OrderToFood/Pages/Resturants/NotFound404.cshtml
@page
@model OrderToFood.Pages.NotFound404Model
@{
}
<div>Your Resturant was Not Found</div>
<div>
    <a asp-page="./List" class="btn btnbtn-primary">Return for all Resturants</a>
</div>

OrderToFood/Pages/Resturants/_Summary.cshtml
@using Resturant.Core
@model ResturantsHotel

<table class="table" style="border:1px solid black">
	<tr>
			<td>@Model.Name</td>
			<td>@Model.Location</td>
			<td>@Model.CusineType</td>
			<td>
				<a class="btn btn-outline-success" asp-page="./Detail" asp-route-resturantId="@Model.Id">Detail</a>
				<a class="btn btn-outline-primary" asp-page="./Edit" asp-route-resturantId="@Model.Id">Edit</a>
				<a class="btn btn-outline-danger" asp-page="./Delete" asp-route-resturantId="@Model.Id">Delete</a>
			</td>
			</tr>
</table>

OrderToFood/Pages/Shared/Components/Resturant/Default.cshtml
@model int

<div class="alert-info">
	There are @Model Resturants here <a class="btn btn-primary" asp-page="/Resturants/List">see them all</a>
</div>

OrderToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrderToFood.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Resturants/List">OrderToFood</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="Resturants/List">Resturants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            
            @RenderSection("footer",required:false)            
            &copy; 2023 - OrderToFood
            <div>
                <vc:resturant></vc:resturant>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>